services:
    server:
        build: 
          context: server
          dockerfile: Dockerfile.dev
        ports: 
            - 5050:5000
        volumes: 
            - ./server/src/:/app/src/
        links:
          - "mongodb:database"
    mongodb:
        image: mongo
        volumes: 
          - ./data:/data/db
    client:
      build: 
        context: client
        dockerfile: Dockerfile.dev
      ports: 
        - 8080:3000